# your domain
domain: smini.cf

# database url
database_url: ""

# cloudflare api
cf_email: "www1@fmini.tk"
cf_key: "e08237165f72afdd40c0e956425ff6d709bd3"

# source definition file
source-files:
  # use local file
  - source.yaml
  # use web file
  - https://example.com/source.yaml
